config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'
  get '/softs', to: 'pages#softs'
  get '/beers', to: 'pages#beers'
  get '/chauds', to: 'pages#chauds'
  get '/cafesfroids', to: 'pages#cafesfroids'
  get '/jusfrais', to: 'pages#jusfrais'
  get '/alcool', to: 'pages#alcool'
  get '/cocktails', to: 'pages#cocktails'
  get '/vins', to: 'pages#vins'
  get '/aperitifs', to: 'pages#aperitifs'
  get '/liqueurs', to: 'pages#vins'
  get '/petitdejeuner', to: 'pages#petitdejeuner'

  get '/dashboard', to: 'pages#dashboard'

   resources :foods
   resources :drinks
   resources :icecreams

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord

  belongs_to :user

  has_one_attached :photo

  validates :category, :name, :description, :price, :photo, presence: true

 # include PgSearch::Model
 #  pg_search_scope :search_by_name,
 #    against: [[ :name , 'A']],
 #    using: {
 #      tsearch: { prefix: true }
 #    }

end

app/models/food.rb
class Food < ApplicationRecord

  belongs_to :user

  has_one_attached :photo

  validates :category, :name, :description, :price, :photo, presence: true

 # include PgSearch::Model
 #  pg_search_scope :search_by_name,
 #    against: [[ :name , 'A']],
 #    using: {
 #      tsearch: { prefix: true }
 #    }

end

app/models/icecream.rb
class Icecream < ApplicationRecord
  belongs_to :user
    has_one_attached :photo

  validates :category, :name, :description, :price, :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :drinks
  has_many :foods
  has_many :icecreams

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
    before_action :set_drink, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]

  def index
      @drinks = Drink.all
  end

  def show
    @drinks = Drink.all
  end

  def new
    @drink = Drink.new
  end

  def edit
  end

  def create
    @drink = Drink.new(drink_params)
    @drink.user = current_user

    if @drink.save
      redirect_to @drink, notice: "Drink créé! Tu picoles trop."
    else
      render :new
    end
  end

  def update
    if @drink.update(drink_params)
      redirect_to @drink, notice: "Drink updated! T'as pensé á rajouté du rhum."
    else
      render :edit
    end
  end

  def destroy
    @drink.destroy
    redirect_to root_path, notice: "Drink détruit! T'as la gueule de bois."
  end

  private

  def set_drink
    @drink = Drink.find(params[:id])
  end

  def drink_params
  params.require(:drink).permit(:category, :name, :description, :price, :cl, :subcat, :photo)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    before_action :set_food, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]

  def index
      @foods = Food.all
  end

  def show
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: "Plat créé! Mmmmh J'adore les Donuts á la mayonnaise."
    else
      render :new
    end
  end

  def update
    if @food.update(food_params)
      redirect_to foods_path, notice: "Plat updated! De la sardine avec du sanglier au beur de cacahuéte? t'es sur de ton coup."
    else
      render :edit
    end
  end

  def destroy
    @food.destroy
    redirect_to root_path, notice: "Food détruit! Les plats diets c'est pas bon."
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
  params.require(:food).permit(:category, :name, :description, :price, :photo)
  end
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
    before_action :set_icecream, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]

  def index
      @icecreams = Icecream.all
  end

  def show
    @icecreams = Icecream.all
  end

  def new
    @icecream = Icecream.new
  end

  def edit
  end

  def create
    @icecream = Icecream.new(icecream_params)
    @icecream.user = current_user

    if @icecream.save
      redirect_to icecreams_path, notice: "Glace créée! Mmmmh Une glace au concombre."
    else
      render :new
    end
  end

  def update
    if @icecream.update(icecream_params)
      redirect_to icecreams_path, notice: "Glace updated! Forcément avec de la vodka c'est toujorus meilheurs."
    else
      render :edit
    end
  end

  def destroy
    @icecream.destroy
    redirect_to root_path, notice: "Glace détruite! La glace au concombre c'est pas bon."
  end

  private

  def set_icecream
    @icecream = Icecream.find(params[:id])
  end

  def icecream_params
  params.require(:icecream).permit(:category, :name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home, :dashboard, :drinks, :beers, :softs, :chauds, :cafefroids, :jusfrais, :alcool, :cocktails, :vins, :aperitifs, :cafesfroids, :liqueur, :petitdejeuner]
  before_action :set_drinks, only: [:home, :dashboard, :drinks, :beers, :softs, :chauds, :cafesfroids, :jusfrais, :alcool, :cocktails, :vins, :aperitifs, :liqueur, :cafesfroids, :petitdejeuner]

  def home
    # if params[:query].present?
    #   @drinks = Drink.search_by_name(params[:query])
    # else
    # @drinks = Drink.all
    # end
  end

  # def index
  #   client = InstagramBasicDisplay::Client.new(auth_token: ENV['TOKEN'])
  #   user = User.first

  #   long_token_request = client.long_lived_token(short_lived_token: user.instagram_token)

  #   if long_token_request.success?
  #     auth_token = token_request.payload.access_token
  #     expires_in = token_request.payload.expires_in
  #     user.update_instagram_token(token: token, expires_in: expires_in)
  #   else
  #     render json: long_token_request.error, status: 400
  #   end
  # end

  def dashboard
    # @drinks = Drink.search_by_name(params[:query])
  end

  private

  def set_drinks
    @drinks = Drink.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
  <% @foods.each do |food| %>
    <% if user_signed_in?  %>
          <div class="card-product m-2">
            <%= image_tag food.photo ,  class: "card-product__img", alt: "Card image cap" %>
            <div class="card-product__infos">
              <h5 class="card-product__title"><%= food.name %></h5>
              <p class="card-product__description"><%= food.description %></p>
              <p class="card-product__price"><small class="text-muted">  € <%= food.price %> </small></p>
              <%= link_to "edit", edit_food_path(food), class: "btn btn-sm btn-outline-primary"  %>
            </div>
          </div>

    <% else %>
          <div class="card-product m-2">
            <%= image_tag food.photo ,  class: "card-product__img", alt: "Card image cap" %>
            <div class="card-product__infos">
              <h5 class="card-product__title"><%= food.name %></h5>
                <p class="card-product__description"><%= food.description %></p>
                <p class="card-product__price"><small class="text-muted">  € <%= food.price %> </small></p>
            </div>
          </div>
        <% end %>
  <% end %>

app/views/icecreams/index.html.erb
<div class="text-center">
Café, canistrelli, Caramel-beurre salé, Castagna, Cédrat Corse, Chocolat noir, Citron, Clémentine IGP corse, Fraise, Framboise, Griotte, Menthe du jardin, Miel AOP corse, Myrte, Noix de coco, Nougat, Nebbiulina (nutella corse), Pêche de vigne, Pistache, Rhum-raisin, Vanille
</div>

<div class="btn-group " role="group" aria-label="Basic example">
  <button type="button" class="btn btn-primary">La Boule €3,20 </button>
  <button type="button" class="btn btn-primary">Chantilly €1,60</button>
  <button type="button" class="btn btn-primary">    Chocolat Maison €2,00</button>
</div>

<% @icecreams.each do |icecream| %>
  <% if user_signed_in?  %>
      <div class="card-product">
        <%= image_tag icecream.photo ,  class: "card-product__img", alt: "Card image cap" %>
        <div class="card-product__infos">
          <h5 class="card-product__title"><%= icecream.name %></h5>
          <p class="card-product__description"><%= icecream.description %></p>
          <p class="card-product__price"><small class="text-muted">  € <%= icecream.price %> </small></p>
          <%= link_to "edit", edit_icecream_path(icecream), class: "btn btn-sm btn-outline-primary"  %>
        </div>
      </div>

  <% else %>
    <div class="card-product">
      <%= image_tag icecream.photo ,  class: "card-product__img", alt: "Card image cap" %>
      <div class="card-product__infos">
        <h5 class="card-product__title"><%= icecream.name %></h5>
        <p class="card-product__description"><%= icecream.description %></p>
        <p class="card-product__price"><small class="text-muted">  € <%= icecream.price %> </small></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/alcool.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Alcool").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></h6>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Alcool").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
    </div>
  </div>
  <% end %>
<% end %>

app/views/pages/aperitifs.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Aperitif").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Aperitif").each do |drink| %>
    <div class="card-product">
        <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
      <div class="card-product__infos">
        <h2 class="card-product__title"> <%= drink.name %> </h2>
        <p class="card-product__description"> <%= drink.description %></p>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>

      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/beers.html.erb
<div class="d-flex justify-content-center">

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card-beer m-2">
        <img src="https://res.cloudinary.com/numama/image/upload/v1620309089/EUROPE/pression_abnsgi.png" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">RIBELLA – RIBELLA</h5>
            <h6 class="card-title">Bière Bio Blonde Ale | 100% orge corse</h6>
            <p class="card-text">Bière à la pression | La Ribella Ribella est une lager 100% corse créant le style de la Corsican Lager. Désaltérante et raffinée.</p>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> Galopin | 12,5 cl | € 2,00 </small></p>
            <p class="card-text text-right"><small class="text-muted"> Demi | 25 cl | € 3,80 </small></p>
            <p class="card-text text-right"><small class="text-muted"> Pinte | 50 cl | € 7,40 </small></p>
          </div>
      </div>
    </div>
      <div class="col">
        <div class="card-beer m-2">
          <img src="https://res.cloudinary.com/numama/image/upload/v1620309384/EUROPE/beerambre_olslys.jpg" class="card-img-top" alt="...">
          <div class="card-body">
              <div class="card-body">
            <h5 class="card-title">SANTA – RIBELLA</h5>
              <h6 class="card-title">Bière Bio Ambrée | Bière Bio Ambrée</h6>
              <p class="card-text">Bière à la pression | Réconfortante et gourmande, cette Milk Stout à la noisette IGP de Cervione.</p>
              <!-- <p class="card-text"><small class="text-muted">5 médailles d'argent au Concours Général de Paris, coup de coeur du Guide Hachette des Bières</small></p> -->
            </div>
              <hr>
              <p class="card-text text-right"><small class="text-muted"> Galopin | 12,5 cl | € 2,30 </small></p>
              <p class="card-text text-right"><small class="text-muted"> Demi | 25 cl | € 4,30 </small></p>
              <p class="card-text text-right"><small class="text-muted"> Pinte | 50 cl | € 8,40 </small></p>
          </div>
        </div>
      </div>
      <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1623349647/EUROPE/Captura_de_Tela_2021-06-10_a%CC%80s_15.27.00_ulvhh0.png" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">FILLE DE JOIE - RIBELLA</h5>
            <h6 class="card-title">Milk Shake IPA Abricot - Romarain</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> 33 cl | € 6,00 </small></p>
          </div>
      </div>
    </div>
    <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1623349596/EUROPE/saleccia_j7w47v.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">SALECCIA - RIBELLA</h5>
            <h6 class="card-title">Beach Gose Eau de Mer - Lime de Tahiti</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> 33 cl | € 6,00 </small></p>
          </div>
      </div>
    </div>
    <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1623349596/EUROPE/eroina_wcskh0.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">EROINA - RIBELLA</h5>
            <h6 class="card-title">Meipa Pomelos</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> 33 cl | € 6,00 </small></p>
          </div>
      </div>
    </div>
  <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1623349777/EUROPE/Captura_de_Tela_2021-06-10_a%CC%80s_15.29.19_jb4cvu.png" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">MISTICA - RIBELLA</h5>
            <h6 class="card-title">Stout - Farine de Châtaigne - AOP Corse</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> 33 cl | € 6,00 </small></p>
          </div>
      </div>
    </div>
  <div class="col">
      <div class="card-beer m-2">
        <img src="https://res.cloudinary.com/numama/image/upload/v1620272409/pvwx56tladye0l1awpii9vsg49af.png" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">PANACHÉ</h5>
            <h6 class="card-title">Bière Bio Blonde Ale + Limonade</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> Demi | 25 cl | € 3,80 </small></p>
            <p class="card-text text-right"><small class="text-muted"> Pinte | 50 cl | € 7,40 </small></p>
          </div>
      </div>
    </div>
    <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1620272514/n8cmct4lqni83iz7pu6i806sx3zz.png" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">MONACO</h5>
            <h6 class="card-title">Bière Bio Blonde Ale + Limonade + Grenadine</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> Demi | 25 cl | € 3,80 </small></p>
            <p class="card-text text-right"><small class="text-muted"> Pinte | 50 cl | € 7,40 </small></p>
          </div>
      </div>
    </div>
    <div class="col">
      <div class="card-beer m-2">
      <img src="https://res.cloudinary.com/numama/image/upload/v1620310621/EUROPE/picon_xlflou.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-body">
          <h5 class="card-title">PICON BIERE</h5>
            <h6 class="card-title">Bière Bio Blonde Ale + Picon</h6>
          </div>
            <hr>
            <p class="card-text text-right"><small class="text-muted"> Demi | 25 cl | € 4,50 </small></p>
            <p class="card-text text-right"><small class="text-muted"> Pinte | 50 cl | € 8,50 </small></p>
          </div>
      </div>
    </div>
  </div>
</div>


  <% @drinks.where(category: 'Bière', subcat: 'Bouteille').each do |drink| %>

  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<%# else %>

<!--   <%# @drinks.where(category: "Bière", subcat: "Bouteille").each do |drink| %>
  <div class="card-product">
      <%#= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%#= drink.name %> </h2>
      <p class="card-product__description"> <%#= drink.description %></p>
      <p class="card-product__price"> <%#= drink.cl %> | € <%#= drink.price %></p>

    </div>
  </div>
  <%# end %>
<%# end %> -->

app/views/pages/cafesfroids.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Thé & Café froid").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Thé & Café froid").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>

    </div>
  </div>
  <% end %>
<% end %>

app/views/pages/chauds.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Boisson chaude").each do |drink| %>
  <div class="card-product">
    <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Boisson chaude").each do |drink| %>
  <div class="card-product">
    <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>

    </div>
  </div>
  <% end %>
<% end %>

app/views/pages/cocktails.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Cocktail").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Cocktail").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="card-product__title"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
    </div>
  </div>
  <% end %>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container mt-5">
  <hr>
 <h5>Un nouveau coktail ou drink ? </h5>

 <%= link_to 'Créer une boisson', new_drink_path, class: 'btn btn-primary'  %>
 <hr>
 <h5>Envie de Cuisiner ? </h5>
 <%= link_to 'Créer une Plat', new_food_path, class: 'btn btn-primary'  %>
 <hr>
  <h5>Une p'tite glace ? </h5>
 <%= link_to 'Créer une Glace', new_icecream_path, class: 'btn btn-primary'  %>
 <hr>
</div>

app/views/pages/liqueurs.html.erb
<% if user_signed_in? %>
  <% @drinks.where(category: "Liqueur").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="text-uppercase"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <div class="d-flex justify-content-around flex-column">
        <%= link_to "edit", edit_drink_path(drink), class: "btn btn-sm btn-outline-primary" %>
        <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>
      </div>

    </div>
  </div>
  <% end %>
<% else %>
  <% @drinks.where(category: "Liqueur").each do |drink| %>
  <div class="card-product">
      <%= image_tag drink.photo, class: "card-product__img", alt: "Card image cap" %>
    <div class="card-product__infos">
      <h2 class="text-uppercase"> <%= drink.name %> </h2>
      <p class="card-product__description"> <%= drink.description %></p>
      <p class="card-product__price"> <%= drink.cl %> | € <%= drink.price %></p>

    </div>
  </div>
  <% end %>
<% end %>

app/views/shared/_category.html.erb
<div class="card-group text-uppercase justify-content-between">
  <div class="col-sm-3 m-1">
    <%= link_to drinks_path do %>
      <div class="card-category">
        Une P'tite Soif
      </div>
    <% end %>
  </div>
  <div class="col-sm-3 m-1">
    <%= link_to foods_path do %>
      <div class="card-category">
        Une P'tite Faim
      </div>
    <% end %>
  </div>
  <div class="col-sm-3 m-1">
    <%= link_to icecreams_path do %>
      <div class="card-category text-uppercase">
        Une P'tite Douceur
      </div>
    <% end %>
  </div>
  <div class="col-sm-3 m-1">
    <%= link_to petitdejeuner_path do  %>
      <div class="card-category text-center">
       Un P'tit Dejeuner
        <!-- breakfast -->
      </div>
    <% end %>
  </div>
</div>
<!--
<div class="card-group text-uppercase">
  <div class="col-sm-4 m-2">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/numama/image/upload/v1619053369/EUROPE/pinelli_uoeek0.png)">
       Vins
      </div>
  </div>
  <div class="col-sm-4 m-2">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/numama/image/upload/v1619053551/EUROPE/ribella2_p9vofv.png)">
    Bierres
    </div>
  </div>
  <div class="col-sm-4 m-2">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/numama/image/upload/v1619053648/EUROPE/cocktails_hg43il.jpg)">
      Cocktails
    </div>
  </div>
</div>
 -->

app/views/shared/_morning_categories.html.erb
<%= link_to petitdejeuner_path, :class=> "card-category card-category--breakfast" do  %>
   Un P'tit Dejeuner
<% end %>
<%= link_to drinks_path, :class=> "card-category card-category--drinks" do %>
    Une P'tite Soif
<% end %>
<%= link_to icecreams_path, :class=> "card-category", :style=> "--grow: 1;" do %>
    Une P'tite Douceur
<% end %>

app/views/shared/_night_categories.html.erb
<%= link_to drinks_path, :class=> "card-category" do %>
    Une P'tite Soif
<% end %>
<%= link_to icecreams_path, :class=> "card-category" do %>
    Une P'tite Douceur
<% end %>
<%= link_to foods_path, :class=> "card-category", :style=> "--grow: 1;" do %>
    Une P'tite Faim
<% end %>